version: '3.9'

services:
  bot_api:
    image: vgolovnin/memgrep:bot
    build:
      context: .
    command: [python3, scripts/start_api.py]
    restart: always
    ports:
    - 127.0.0.1:5000:5000
    volumes:
    - ./prod.session:/var/www/memgrep/prod.session
    - ./.env:/var/www/memgrep/.env


  redis:
    image: redis/redis-stack-server:7.0.6-RC5
    restart: always
    ports:
    - 127.0.0.1:6379:6379
    volumes:
    - ./redis:/data

  minio:
    image: minio/minio:RELEASE.2023-01-31T02-24-19Z
    ports:
    - 127.0.0.1:9000:9000
    - 127.0.0.1:9001:9001
    volumes:
    - ./minio_storage:/data
    env_file:
    - .env
    command: server --console-address ":9001" /data
