version: '3.9'

services:
  bot_api:
    image: bot_api:latest
    build:
      context: .
    restart: always
    ports:
    - 127.0.0.1:5000:5000
    volumes:
    - ./bot_api:/app

  redis:
    image: redis:7.0.8
    restart: always
    ports:
    - 127.0.0.1:6379:6379
    volumes:
    - ./redis:/data

  minio:
    image: minio/minio:RELEASE.2023-01-31T02-24-19Z
    ports:
    - 127.0.0.1:9000:9000
    - 127.0.0.1:9001:9001
    volumes:
    - ./minio_storage:/data
    env_file:
    - .env
    command: server --console-address ":9001" /data
